name: feathernotes
base: core22
adopt-info: feathernotes
grade: stable
confinement: strict
compression: lzo
architectures:
  - build-on: amd64
    build-for: amd64
    
layout:
  /usr/share/qt5:
    symlink: $SNAP/kf5/usr/share/qt5
  /usr/share/X11:
    symlink: $SNAP/kf5/usr/share/X11
  /usr/lib/$CRAFT_ARCH_TRIPLET/libhunspell-1.7.so.0:
    symlink: $SNAP/kf5/usr/lib/$CRAFT_ARCH_TRIPLET/libhunspell-1.7.so.0
  /usr/lib/$CRAFT_ARCH_TRIPLET/libXext.so.6:
    symlink: $SNAP/kf5/usr/lib/$CRAFT_ARCH_TRIPLET/libXext.so.6  
  /usr/lib/$CRAFT_ARCH_TRIPLET/libEGL.so.1:
    symlink: $SNAP/kf5/usr/lib/$CRAFT_ARCH_TRIPLET/libEGL.so.1
  /usr/lib/$CRAFT_ARCH_TRIPLET/libGL.so.1:
    symlink: $SNAP/kf5/usr/lib/$CRAFT_ARCH_TRIPLET/libGL.so.1
    
  
slots:
  feathernotes:
    interface: dbus
    bus: session
    name: com.github.tsujan.feathernotes

apps:
  feathernotes:
    command: usr/bin/feathernotes
    extensions:
      - kde-neon
    plugs:
      - home
      - network
      - network-status
      - optical-drive
      - removable-media
    common-id: com.github.tsujan.feathernotes
    desktop: usr/share/applications/feathernotes.desktop
    
    
parts:
  feathernotes:
    source: https://github.com/tsujan/FeatherNotes.git
    plugin: cmake
    parse-info: [usr/share/metainfo/feathernotes.metainfo.xml]
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
    build-snaps:
      - cmake
    build-packages:
      - build-essential
      - libxext-dev
      - libx11-dev
      - qtbase5-dev
      - libhunspell-dev
    override-pull: |
      craftctl default
      craftctl set version=$(git describe --tags --abbrev=0 | cut -c 2-)
  

   
