name: feathernotes
base: core22
adopt-info: feathernotes
grade: stable
confinement: strict
compression: lzo
architectures:
  - build-on: amd64
    build-for: amd64

slots:
  feathernotes:
    interface: dbus
    bus: session
    name: com.github.tsujan.feathernotes

apps:
  feathernotes:
    command: usr/bin/feathernotes
    extensions:
      - kde-neon
    plugs:
      - home
      - raw-usb
      - network
      - network-status
      - optical-drive
      - removable-media
    common-id: com.github.tsujan.feathernotes
    desktop: usr/share/applications/feathernotes.desktop
    
    
parts:
  feathernotes:
    source: https://github.com/tsujan/FeatherNotes.git
    after: [hunspell]
    plugin: cmake
    parse-info: [usr/share/metainfo/feathernotes.metainfo.xml]
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
    build-snaps:
      - kf5-5-104-qt-5-15-8-core22-sdk
      - cmake
    build-packages:
      - build-essential
      - libxext-dev
      - libx11-dev
      - qtbase5-dev
    override-pull: |
      craftctl default
      craftctl set version=$(git describe --tags --abbrev=0)
   
  hunspell:
    source: https://github.com/hunspell/hunspell.git
    source-tag: 'v1.7.2'
    plugin: autotools
    build-packages:
      - build-essential
      - autoconf 
      - automake 
      - autopoint 
      - libtool
    override-prime: |
      craftctl default
      ldconfig
